[general]
name = "matmul"
license = "Apache-2.0"
version = 1
backends = ["cuda"]

[general.hub]
repo-id = "rightnow-ai/matmul"

[torch]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.matmul]
backend = "cuda"
depends = ["torch"]
src = ["matmul_cuda/kernel.cu"]
